---
- name: Ensure OpenSSL is installed
  ansible.builtin.package:
    name: openssl
    state: present

- name: Generate private key
  ansible.builtin.openssl_privatekey:
    path: "{{ private_key_path }}"
    size: "{{ ssl_key_size }}"

- name: Generate self-signed certificate
  ansible.builtin.openssl_certificate:
    path: "{{ cert_path }}"
    privatekey_path: "{{ private_key_path }}"
    provider: selfsigned
